server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

  cloud:
    consul:
      host: 192.168.200.160
      port: 8500
      discovery:
        service-name: ${spring.application.name}
